package app.zimly.backup.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF96416B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD8E6)
val md_theme_light_onPrimaryContainer = Color(0xFF3D0025)
val md_theme_light_secondary = Color(0xFF735762)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFED9E6)
val md_theme_light_onSecondaryContainer = Color(0xFF2A151E)
val md_theme_light_tertiary = Color(0xFF7E5538)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDCC6)
val md_theme_light_onTertiaryContainer = Color(0xFF301401)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1A1C)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1A1C)
val md_theme_light_surfaceVariant = Color(0xFFF1DEE3)
val md_theme_light_onSurfaceVariant = Color(0xFF504348)
val md_theme_light_outline = Color(0xFF827378)
val md_theme_light_inverseOnSurface = Color(0xFFF9EEF0)
val md_theme_light_inverseSurface = Color(0xFF352F31)
val md_theme_light_inversePrimary = Color(0xFFFFAFD1)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF96416B)
val md_theme_light_outlineVariant = Color(0xFFD4C2C7)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFAFD1)
val md_theme_dark_onPrimary = Color(0xFF5C113C)
val md_theme_dark_primaryContainer = Color(0xFF782953)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD8E6)
val md_theme_dark_secondary = Color(0xFFE1BDCA)
val md_theme_dark_onSecondary = Color(0xFF412A34)
val md_theme_dark_secondaryContainer = Color(0xFF593F4A)
val md_theme_dark_onSecondaryContainer = Color(0xFFFED9E6)
val md_theme_dark_tertiary = Color(0xFFF2BB98)
val md_theme_dark_onTertiary = Color(0xFF49280F)
val md_theme_dark_tertiaryContainer = Color(0xFF633E23)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDCC6)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1A1C)
val md_theme_dark_onBackground = Color(0xFFEBE0E2)
val md_theme_dark_surface = Color(0xFF1F1A1C)
val md_theme_dark_onSurface = Color(0xFFEBE0E2)
val md_theme_dark_surfaceVariant = Color(0xFF504348)
val md_theme_dark_onSurfaceVariant = Color(0xFFD4C2C7)
val md_theme_dark_outline = Color(0xFF9D8C92)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1A1C)
val md_theme_dark_inverseSurface = Color(0xFFEBE0E2)
val md_theme_dark_inversePrimary = Color(0xFF96416B)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFAFD1)
val md_theme_dark_outlineVariant = Color(0xFF504348)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF8A4A68)
