name: Release to Production
on: workflow_dispatch

jobs:
  release:
    # Add permissions for managing GH releases
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Read version from gradle.properties
        id: set_version
        run: echo "version=`./gradlew -q getVersion`" > $GITHUB_OUTPUT
      - name: Publish GH Release ${{ steps.set_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release edit ${{ steps.set_version.outputs.version }} --tag ${{ steps.set_version.outputs.version }} --draft=false
      - name: Patch applicationId for Play Store
        run: sed -i 's/applicationId = "app.zimly.backup"/applicationId = "io.zeitmaschine.zimzync"/g' app/build.gradle.kts
      - name: Promote Play Store Release
        env:
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: ./gradlew promoteArtifact --from-track alpha --promote-track production