name: Release App
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Read version from gradle.properties
        id: set_version
        run: echo "version=`./gradlew -q getVersion`" >> $GITHUB_OUTPUT
      - name: Print version
        run: echo ${{ steps.set_version.outputs.version }}
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: gh release edit ${{ steps.set_version.outputs.version }} --tag ${{ steps.set_version.outputs.version }} --draft=false
