name: Release to Alpha Channel
on: workflow_dispatch

jobs:

  verify-release:
    name: Run Verification Steps
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      draft-exists: ${{ steps.draft_release.outputs.exists }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Read version from gradle.properties
        id: set_version
        run: echo "version=`./gradlew -q getVersion`" > $GITHUB_OUTPUT
      - name: Check for existing draft ${{ steps.set_version.outputs.version }}
        id: draft_release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: echo "exists=$(gh release list --limit 100 --json name,tagName,isDraft | jq --arg TAG ${{ steps.set_version.outputs.version }} 'map(select(.isDraft == true and .tagName == $TAG)) | length > 0')" > $GITHUB_OUTPUT
      - name: Check for existing release ${{ steps.set_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: |
          exists=$(gh release list --limit 100 --json name,tagName,isDraft | jq --arg TAG ${{ steps.set_version.outputs.version }} 'map(select(.isDraft == false and .tagName == $TAG)) | length > 0')
          if $exists ; then
            echo "Release ${{ steps.set_version.outputs.version }} already exists, exiting"
            exit 1
          fi

  draft-release:
    name: Create draft release
    needs: [verify-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Draft exists
        run: echo ${{ needs.verify-release.outputs.draft-exists }}
      - name: Create draft?
        run: echo ${{ ! needs.verify-release.outputs.draft-exists }}
      - name: Create Draft Release
        if: ${{ ! needs.verify-release.outputs.draft-exists }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
        with:
          tag_name: ${{ needs.verify-release.outputs.version }}
          release_name: Release ${{ needs.verify-release.outputs.version }}
          draft: true

      - name: Update release notes
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
          TAG: ${{ needs.verify-release.outputs.version }}
        run: gh release edit $TAG -F ${{ github.workspace }}/release-notes/whatsnew-en-GB

